name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt
        run: |
          choco install qt5-default -y
          set PATH=C:\Qt\5.15.2\msvc2019_64\bin;%PATH%

      - name: Build project
        run: |
          cd ttt
          qmake ttt.pro
          nmake
