name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake

      - name: Build project
        run: |
          cd ttt
          qmake ttt.pro
          make
